apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes-monolith
  namespace: quotes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotes-monolith
  template:
    metadata:
      labels:
        app: quotes-monolith
    spec:
      containers:
        - name: quotes-monolith
          image: samipn/quotes-monolith:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: quotes-monolith
  namespace: quotes-app
spec:
  type: NodePort
  selector:
    app: quotes-monolith
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30081
